# Generated by Django 5.0 on 2023-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
